FROM node:22

WORKDIR /app

# Install dependencies
COPY script/validator_script.js .
COPY script/package.json .
COPY script/package-lock.json .

RUN npm install

ENTRYPOINT ["node", "validator_script.js"]
