services:
  script:
    build:
      context: .
      dockerfile: docker/Dockerfile.script
    volumes:
      - ./output:/app/output

  dapp:
    build:
      context: ../dapp
      dockerfile: ../docker/Dockerfile.dapp
    ports:
      - "3000:3000"
    env_file:
      - .env
    restart: unless-stopped
